heck_release_file()
        # tc3_check_eload_file()
        # tc4_check_firmware_file()
        # tc5_open_browser(self.driver)
        # tc6_browser_tab_title(self.driver)
        # tc7_scannetwork_enablestate(self.driver)
        # tc8_scanNetworkstate(self.driver)
        # tc9_devicedetails(self.driver)
        # tc10_addressText(self.driver) 
        # tc11_defaultIp(self.driver)
        # tc12_dynamicIp(self.driver)
        # tc13_invalidIP(self.driver)
        # tc14_unreachableIP(self.driver)
        # tc15_ImageCompare(self.driver)
        # tc16_sw_hw_details(self.driver)
        # tc17_updatefirmwarebutton(self.driver)
        # tc18_updatefirmware(self.dr